#!/usr/bin/env node
/**
 * Regenerate js/skillfile.js from skill/study-deck.skill.
 *
 * The skill is embedded as base64 rather than fetched at runtime so the
 * in-app "export the skill to Claude" button keeps working offline and from a
 * home-screen install.
 *
 * Run after replacing the skill: npm run embed-skill
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'skill', 'study-deck.skill');
const target = path.join(root, 'js', 'skillfile.js');

if (!fs.existsSync(source)) {
  console.error(`Missing ${source}`);
  process.exit(1);
}

const bytes = fs.readFileSync(source);
const sha1 = crypto.createHash('sha1').update(bytes).digest('hex').slice(0, 8);
const chunks = bytes.toString('base64').match(/.{1,100}/g) ?? [];

const out = `// AUTO-GENERATED by tools/embed-skill.mjs — do not edit by hand.
// Source: skill/study-deck.skill (${bytes.length} bytes, sha1 ${sha1})

export const SKILL_FILENAME = 'study-deck.skill';
export const SKILL_BYTES = ${bytes.length};
export const SKILL_BASE64 =
${chunks.map((c) => `  '${c}'`).join(' +\n')};
`;

fs.writeFileSync(target, out);
console.log(`Embedded ${bytes.length} bytes (sha1 ${sha1}) into js/skillfile.js`);
